[package]
name = "backend_vulkan_win32"
version = "0.1.0"
edition = "2021"

[dependencies]
gfx = {path = "../gfx"}
backend_vulkan = { path = "../backend_vulkan" }
plateform_win32 = {path = "../plateform_win32"}
ash = "0.37.0"
windows = { version = "0.37.0", features = [ "Win32"] }