[workspace]
members = [
    "crates/engine/*",
    "crates/editor/",
    "crates/main/"
]
default-members = ["crates/editor/"]

[profile.production]
inherits = "release"
opt-level = 3
lto = "fat"
incremental = false
codegen-units = 1