[package]
name = "backend_vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
gfx = {path = "../gfx"}
maths = {path = "../maths"}
maths_operators = {path = "../maths_operators"}
ash = "0.37.0"
gpu-allocator = "0.18.0"