[package]
name = "plateform_wayland"
version = "0.1.0"
edition = "2021"

[dependencies]
plateform = {path = "../../common/plateform"}
maths = { path = "../../maths" }
wayland-client = "0.31.2"
smithay-client-toolkit = "0.18.1"
raw-window-handle = "0.5.2"