[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
shader_compiler = { path = "../shader_compiler" }
gfx = { path = "../common/gfx" }
plateform = { path = "../common/plateform" }

legion = "0.4.0"
gfx-maths = "0.2.8"