[package]
name = "resl"
version = "0.1.0"
edition = "2021"
test = true

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
lalrpop-util = { version = "0.20.0", features = ["lexer"] }
display_json = "0.2.1"
serde = { version = "1.0.188", features = ["rc"] }
serde_json = "1.0.107"