[package]
name = "gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
maths = { path = "../../maths" }
plateform = { path = "../plateform" }
enumflags2 = "0.7.5"
logger = { path = "../../logger" }
ecs = { path = "../../ecs" }
resl = { path = "../resl" }
shader_base = { path = "../gfx_types" }