[package]
name = "imgui-bindings"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "cimgui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.50"
bindgen = "0.69.2"
cc = "1.0.79"
cfg-if = "1.0.0"