name: Windows x64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        components: clippy
    - uses: Swatinem/rust-cache@v1 
    - name: Clippy
      run: cargo clippy --all-targets --no-deps
    - name: Tests
      run: cargo test --all
    - name: Build-Editor
      run: cargo build --verbose